"""Regenerate every table of paper-two-regimes from the committed pre-registered results.
Run from the paper directory: .venv/bin/python figures/make_tables.py  (uses ../paper-plco-hypergraph/results)."""
import glob, pathlib, numpy as np, pandas as pd
SRC = pathlib.Path(__file__).resolve().parents[1]
OUT = pathlib.Path(__file__).resolve().parents[1] / "tables"
NAME = {"cand_eicu_regime": "eICU regimes", "cand_mimic4_regime": "MIMIC-IV regimes", "cand_nhanes": "NHANES mortality",
        "sweep_42739": "road safety", "cand_acs_income": "ACS income", "cand_airbnb": "Airbnb listings",
        "cand_higgs": "ATLAS Higgs", "cand_porto": "Porto Seguro"}
REG = ["cand_eicu_regime", "cand_mimic4_regime", "cand_nhanes", "sweep_42739"]
STR = ["cand_acs_income", "cand_airbnb", "cand_higgs", "sweep_42737", "sweep_46654", "sweep_46703"]
def nm(d): return NAME.get(d, d.replace("sweep_", "OpenML ").replace("cand_", ""))
def load(sub):
    fs = sorted(glob.glob(str(SRC / f"results/{sub}/*.csv"))); return pd.concat([pd.read_csv(f) for f in fs], ignore_index=True)
def panels(sub):
    x = load(sub); m = x[x.kind == "auroc"].groupby(["dataset", "model"]).value.mean().unstack("model")
    lk = {int(c.split("_")[1]): c for c in m.columns if c.startswith("lca_")}
    m["lca20"] = m[[lk[k] for k in sorted(lk) if k <= 20]].max(axis=1); m["diff"] = m["values"] - m.panels_tree
    m["Kneed"] = [min([k for k in sorted(lk) if m.loc[d, lk[k]] >= 0.95 * m.loc[d, "panels_tree"]] or [np.inf]) for d in m.index]
    return m
def esc(s): return s.replace("_", "\\_")

def t_dissociation():
    dv, mi = panels("rrstruct"), panels("rrmirror")
    rows = []
    for grp, ds in (("Protocol-driven", REG), ("Structural", STR), ("Unclassified", [d for d in dv.index if d not in REG + STR])):
        for d in ds:
            rows.append((grp, nm(d), dv.loc[d, "values"], dv.loc[d, "panels_tree"], dv.loc[d, "diff"], mi.loc[d, "diff"]))
    with open(OUT / "dissociation.tex", "w") as f:
        f.write("% generated by figures/make_tables.py -- do not edit\n\\begin{tabular}{llrrrr}\n\\toprule\n")
        f.write(" & Dataset & Values & Presences & Difference & Mirror \\\\\n\\midrule\n"); last = None
        for grp, d, v, p_, df, mf in rows:
            g = grp if grp != last else ""; last = grp
            f.write(f"{g} & {esc(d)} & {v:.3f} & {p_:.3f} & ${df:+.3f}$ & ${mf:+.3f}$ \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")
    return len(rows)

def t_latent():
    dv = panels("rrstruct"); x = load("rrstruct"); npan = x.groupby("dataset").n_panels.first()
    s = x[x.kind == "sites_purity"].groupby("dataset").value.max(); a = x[x.kind == "sites"].groupby("dataset").value.max()
    with open(OUT / "latent.tex", "w") as f:
        f.write("% generated by figures/make_tables.py -- do not edit\n\\begin{tabular}{lrrrrr}\n\\toprule\n")
        f.write("Dataset & Panels & Tree & Pairwise & Mixture & $K$ \\\\\n\\midrule\n")
        for d in dv.sort_values("panels_tree", ascending=False).index:
            f.write(f"{esc(nm(d))} & {int(npan[d])} & {dv.loc[d,'panels_tree']:.3f} & {dv.loc[d,'panels_l1']:.3f} & {dv.loc[d,'lca20']:.3f} & {int(dv.loc[d,'Kneed'])} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")
    return {d: (float(s.get(d, np.nan)), float(a.get(d, np.nan))) for d in ("cand_eicu_regime", "cand_mimic4_regime")}

def t_maskinc():
    x = load("maskinc"); w = x[x.arm != "mask_full"].groupby(["dataset", "q", "arm"]).auprc.median().unstack("arm")
    gf = (w["values+mask_full"] - w["values"]).unstack("q"); gk = (w["values+mask_kept"] - w["values"]).unstack("q")
    with open(OUT / "maskinc.tex", "w") as f:
        f.write("% generated by figures/make_tables.py -- do not edit\n\\begin{tabular}{lrrrrrr}\n\\toprule\n")
        f.write("Dataset & $q{=}1$ & $0.75$ & $0.5$ & $0.25$ & $0.1$ & kept $0.1$ \\\\\n\\midrule\n")
        for d in gf.sort_values(0.1, ascending=False).index:
            f.write(f"{esc(nm(d))} & " + " & ".join(f"{gf.loc[d,q]:.3f}" for q in (1.0, 0.75, 0.5, 0.25, 0.1)) + f" & {gk.loc[d,0.1]:.3f} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")
    return gf.median().to_dict()

def t_smdi():
    x = load("smdi"); x = x[x.panel >= 0]
    g = x.groupby(["dataset", "panel"]).agg(av=("auroc_values", "first"), ap=("auroc_panels", "first"),
                                            ab=("auroc_both", "first"), share=("imp_share_values", "mean")).dropna()
    masked = g[((g.share <= 0.10) & (g.av >= 0.80)) | ((g.share >= 0.90) & (g.ap >= 0.80))]
    d = g.groupby(level=0).agg(panels=("share", "size"), share=("share", "mean"), av=("av", "mean"), ap=("ap", "mean"))
    dis = int((np.sign(d.share - 0.5) != np.sign(d.av - d.ap)).sum())
    ex = g.loc["sweep_42333"] if "sweep_42333" in g.index.get_level_values(0) else None
    with open(OUT / "smdi.tex", "w") as f:
        f.write("% generated by figures/make_tables.py -- do not edit\n\\begin{tabular}{lrrrr}\n\\toprule\n")
        f.write("Panel & Values alone & Presences alone & Both & Importance to values \\\\\n\\midrule\n")
        if ex is not None:
            for i in ex.sort_values("share").index:
                f.write(f"{int(i)} & {ex.loc[i,'av']:.3f} & {ex.loc[i,'ap']:.3f} & {ex.loc[i,'ab']:.3f} & {ex.loc[i,'share']:.3f} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")
    return len(masked), len(g), len(d) - dis

def t_withinhosp():
    """WITHINHOSP (../paper-plco-hypergraph/prereg/WITHINHOSP.md): the same panels, refitted inside
    one hospital. Returns per collection: pooled, values pooled, within-site, values within-site,
    and the number of sites that contributed."""
    out = {}
    for tag in ("eicu", "mimic4"):
        f = SRC / f"results/withinhosp/{tag}.csv"
        if not f.exists(): continue
        d = pd.read_csv(f); pool, site = d[d.site == "POOLED"], d[d.site != "POOLED"]
        out[tag] = (float(pool.pooled_on_site.median()), float(pool.values_on_site.median()),
                    float(site.within_site.median()), float(site.values_on_site.median()),
                    int(site.site.nunique()))
    return out


def t_notreat():
    """NOTREAT (../paper-plco-hypergraph/prereg/NOTREAT.md): the dissociation with all fifteen
    treatment columns removed. Returns per run: median panels_tree, median values, median gap."""
    out = {}
    for tag in ("eicu", "mimic4", "eicu-mirror"):
        f = SRC / f"results/notreat/{tag}.csv"
        if not f.exists(): continue
        d = pd.read_csv(f); a = d[d.kind == "auroc"]
        w = a.pivot_table(index="panel", columns="model", values="value")
        out[tag] = (float(w.panels_tree.median()), float(w["values"].median()),
                    float((w.panels_tree - w["values"]).dropna().median()))
    return out


def counts():
    dv, mi = panels("rrstruct"), panels("rrmirror"); site = t_latent()
    g = t_maskinc(); n = t_dissociation(); nmask, npan, sagree = t_smdi()
    wh = t_withinhosp(); nt = t_notreat()
    d1 = int((mi.reindex(REG)["diff"] <= -0.15).sum()); d2 = int((mi.reindex(STR)["diff"] >= 0.10).sum())
    agree = int((np.sign(mi["diff"]) == np.sign(dv.reindex(mi.index)["diff"])).sum())
    k = int((dv.lca20 >= 0.95 * dv.panels_tree).sum()); k10 = int((dv.Kneed <= 10).sum())
    l1 = int((dv.panels_l1 >= 0.98 * dv.panels_tree).sum())
    with open(OUT / "counts.tex", "w") as f:
        f.write("% generated by figures/make_tables.py -- do not edit\n")
        for k_, v in [("NDatasets", len(dv)), ("DOne", d1), ("DTwo", d2), ("SignAgree", agree), ("MixMatch", k),
                      ("KTen", k10), ("PairMatch", l1), ("EicuPurity", f"{site['cand_eicu_regime'][0]:.2f}"),
                      ("EicuAmi", f"{site['cand_eicu_regime'][1]:.3f}"), ("MimicPurity", f"{site['cand_mimic4_regime'][0]:.2f}"),
                      ("GainTenth", f"{g[0.1]:.3f}"), ("GainQuarter", f"{g[0.25]:.3f}"),
                      ("MaskedPanels", nmask), ("NPanels", npan), ("SmdiAgree", sagree),
                      # WITHINHOSP: the dependence with the hospital held fixed
                      ("WhEicuPooled", f"{wh['eicu'][0]:.3f}"), ("WhEicuWithin", f"{wh['eicu'][2]:.3f}"),
                      ("WhEicuValues", f"{wh['eicu'][3]:.3f}"), ("WhEicuSites", wh["eicu"][4]),
                      ("WhMimicPooled", f"{wh['mimic4'][0]:.3f}"), ("WhMimicWithin", f"{wh['mimic4'][2]:.3f}"),
                      ("WhMimicValues", f"{wh['mimic4'][3]:.3f}"), ("WhMimicSites", wh["mimic4"][4]),
                      # NOTREAT: the dissociation without the fifteen treatment columns
                      ("NtEicuPanels", f"{nt['eicu'][0]:.3f}"), ("NtEicuValues", f"{nt['eicu'][1]:.3f}"),
                      ("NtMimicPanels", f"{nt['mimic4'][0]:.3f}"), ("NtMimicValues", f"{nt['mimic4'][1]:.3f}"),
                      ("NtMirrorPanels", f"{nt['eicu-mirror'][0]:.3f}"),
                      ("NtEicuGap", f"{nt['eicu'][2]:.3f}")]:
            f.write(f"\\newcommand{{\\{k_}}}{{{v}}}\n")
    print(f"dissociation.tex {n} rows; latent.tex; maskinc.tex; counts.tex")
    print(f"  D1 {d1}/4  D2 {d2}/6  sign agree {agree}/{len(mi)}  mixture matches {k}/{len(dv)}  pairwise matches {l1}/{len(dv)}")
    print(f"  eICU purity {site['cand_eicu_regime'][0]:.2f} AMI {site['cand_eicu_regime'][1]:.3f}; MIMIC purity {site['cand_mimic4_regime'][0]:.2f}")
    print(f"  median mask gain: q=0.1 {g[0.1]:.4f}, q=0.25 {g[0.25]:.4f}, q=1.0 {g[1.0]:.4f}")
    print(f"  smdi: {nmask} masked panels of {npan}; dataset-level verdict agrees on {sagree}")
if __name__ == "__main__": counts()
